package pe.edu.upc.micasita.Micasitaplataform.Flujo;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
//import static pe.edu.upc.onewebs.OnewebsApplicationTests.inicializarChromeDriver;
import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.ActiveProfiles;


import java.util.*;
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
public class MicasitaPropietarioTest {

    @LocalServerPort
    private int port;

    private WebDriver driver=inicializarChromeDriver();
    public static WebDriver inicializarChromeDriver() {
        // Establecer la ruta del ChromeDriver
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\HP\\Downloads\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe");
        ChromeOptions options = new ChromeOptions();
        // Añadir opciones deseadas aquí
        options.addArguments("--disable-notifications");
        options.addArguments("--remote-allow-origins=*");
        return new ChromeDriver(options);
    }
    String getServerUrl(String endpoint) {
        assert port > 0;

        if (!endpoint.startsWith("/")) {
            endpoint = "/" + endpoint;
        }
        return "http://localhost:" + port + endpoint;
    }
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void micasitaPropietario() {
        driver.get("http://localhost:4200/register");

        ExpectedCondition<Boolean> pageLoadCondition = driver -> ((JavascriptExecutor) driver)
                .executeScript("return document.readyState").equals("complete");

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5L));
        wait.until(pageLoadCondition);
        driver.manage().window().setSize(new Dimension(1552, 832));
        WebElement name = driver.findElement(By.name("name"));
        name.sendKeys("Juan");
        //driver.findElement(By.name("name")).click();
        // driver.findElement(By.name("name")).sendKeys("Juan");
       // Thread.sleep(1000);
        //driver.findElement(By.name("dni")).click();
        // driver.findElement(By.name("dni")).sendKeys("11111111");
        WebElement dni = driver.findElement(By.name("dni"));
        dni.sendKeys("11111111");
       // Thread.sleep(1000);
        // driver.findElement(By.name("email")).click();
        // driver.findElement(By.name("email")).sendKeys("juan@gmail.com");
        WebElement email = driver.findElement(By.name("email"));
        email.sendKeys("juan@gmail.com");
       // Thread.sleep(1000);
        // driver.findElement(By.name("password")).click();
        // driver.findElement(By.name("password")).sendKeys("123456789");
        WebElement password = driver.findElement(By.name("password"));
        password.sendKeys("123456789");
        //Thread.sleep(1000);
        // driver.findElement(By.name("phone")).click();
        // driver.findElement(By.name("phone")).sendKeys("987654321");
        WebElement phone = driver.findElement(By.name("phone"));
        phone.sendKeys("987654321");
        //Thread.sleep(1000);
        //driver.findElement(By.name("address")).click();
        //driver.findElement(By.name("address")).sendKeys("AV.MARIAN San Miguel");
        WebElement address = driver.findElement(By.name("address"));
        address.sendKeys("AV.MARIAN San Miguel");
        //Thread.sleep(1000);

        //driver.findElement(By.cssSelector("button:nth-child(9)")).click();
        WebElement btnRegistrar = driver.findElement(By.cssSelector("button:nth-child(9)"));
        btnRegistrar.click();
       /* {
            WebElement element = driver.findElement(By.cssSelector(".mdc-button > .mat-mdc-button-touch-target"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".mat-mdc-menu-trigger > .mat-mdc-button-touch-target"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }*/
        //Thread.sleep(1000);
        wait.until(pageLoadCondition);

        //driver.findElement(By.cssSelector(".mat-mdc-menu-trigger > .mat-mdc-button-touch-target")).click();
        WebElement btnMenu = driver.findElement(By.cssSelector(".mat-mdc-menu-trigger > .mat-mdc-button-touch-target"));
        btnMenu.click();
       /* {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".mat-mdc-menu-item:nth-child(1) .mat-mdc-button-touch-target"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".mat-mdc-menu-item:nth-child(2) .mat-mdc-button-touch-target"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }*/
        //driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label")).click();
        WebElement btnFocused = driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label"));
        btnFocused.click();
        //driver.findElement(By.id("mat-input-0")).click();
        WebElement inputName = driver.findElement(By.id("mat-input-0"));
        inputName.click();
        {
            WebElement element = driver.findElement(By.cssSelector(".mat-stepper-next:nth-child(1) > .mat-mdc-button-touch-target"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".mat-stepper-next:nth-child(1) > .mdc-button__label"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        //driver.findElement(By.id("mat-input-0")).sendKeys("Juan");
        inputName.sendKeys("Juan");
        //driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label")).click();
        btnFocused = driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label"));
        btnFocused.click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        //driver.findElement(By.cssSelector("#venta .mdc-label")).click();
        WebElement venta = driver.findElement(By.cssSelector("#venta .mdc-label"));
        venta.click();
       // driver.findElement(By.cssSelector("#mat-select-value-1 > .mat-mdc-select-placeholder")).click();
        WebElement matSelectValue1 = driver.findElement(By.cssSelector("#mat-select-value-1 > .mat-mdc-select-placeholder"));
        matSelectValue1.click();
        //driver.findElement(By.cssSelector("#mat-option-0 > .mdc-list-item__primary-text")).click();
        WebElement matOption0 = driver.findElement(By.cssSelector("#mat-option-0 > .mdc-list-item__primary-text"));
        matOption0.click();
        {
            WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .mat-stepper-previous > .mat-mdc-button-touch-target"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .mat-stepper-next > .mat-mdc-button-touch-target"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        //driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label")).click();
        btnFocused = driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label"));
        btnFocused.click();
        {
            WebElement element = driver.findElement(By.cssSelector("div:nth-child(2) > .mat-stepper-next:nth-child(2) > .mat-mdc-button-touch-target"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        //driver.findElement(By.cssSelector("#mat-select-value-3 > .mat-mdc-select-placeholder")).click();
        WebElement matSelectValue3 = driver.findElement(By.cssSelector("#mat-select-value-3 > .mat-mdc-select-placeholder"));
        matSelectValue3.click();
        //driver.findElement(By.cssSelector("#mat-option-6 > .mdc-list-item__primary-text")).click();
        WebElement matOption6 = driver.findElement(By.cssSelector("#mat-option-6 > .mdc-list-item__primary-text"));
        matOption6.click();
       // driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label")).click();
        btnFocused = driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label"));
        btnFocused.click();
       // driver.findElement(By.cssSelector(".mat-mdc-select-placeholder")).click();
        WebElement matMdcSelectPlaceholder = driver.findElement(By.cssSelector(".mat-mdc-select-placeholder"));
        matMdcSelectPlaceholder.click();
        //driver.findElement(By.id("mat-option-29")).click();
        WebElement matOption29 = driver.findElement(By.id("mat-option-29"));
        matOption29.click();
        //driver.findElement(By.id("sol-input")).click();
        WebElement solInput = driver.findElement(By.id("sol-input"));
        solInput.click();
        //driver.findElement(By.id("mat-input-1")).click();
        WebElement matInput1 = driver.findElement(By.id("mat-input-1"));
        matInput1.click();
        {
            WebElement element = driver.findElement(By.cssSelector(".files-container_case-1 .mat-mdc-button-touch-target"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".files-container_case-1 .mdc-button__label"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        //driver.findElement(By.id("mat-input-1")).sendKeys("1498");
        matInput1.sendKeys("1498");
        //driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label")).click();
        btnFocused = driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label"));
        btnFocused.click();
       // driver.findElement(By.id("fileInput")).sendKeys("C:\\fakepath\\images2.jpg")
        WebElement fileInput = driver.findElement(By.id("fileInput"));
        fileInput.sendKeys("C:\\fakepath\\images2.jpg");
       // driver.findElement(By.id("mat-input-2")).click();
        WebElement matInput2 = driver.findElement(By.id("mat-input-2"));
        matInput2.click();
        //driver.findElement(By.id("mat-input-2")).sendKeys("15");
        matInput2.sendKeys("15");


        //driver.findElement(By.id("mat-input-3")).click();
        WebElement matInput3 = driver.findElement(By.id("mat-input-3"));
        matInput3.click();
       // driver.findElement(By.id("mat-input-3")).sendKeys("3");
        matInput3.sendKeys("3");

        //driver.findElement(By.id("mat-input-4")).click();
        WebElement matInput4 = driver.findElement(By.id("mat-input-4"));
        matInput4.click();
        //driver.findElement(By.id("mat-input-4")).sendKeys("2");
        matInput4.sendKeys("2");
        //driver.findElement(By.id("mat-input-5")).click();
        //driver.findElement(By.id("mat-input-5")).click();
        WebElement matInput5 = driver.findElement(By.id("mat-input-5"));
        matInput5.click();
        //driver.findElement(By.id("mat-input-5")).sendKeys("0");
        matInput5.sendKeys("0");

        //driver.findElement(By.id("mat-input-6")).click();
        WebElement matInput6 = driver.findElement(By.id("mat-input-6"));
        matInput6.click();
       // driver.findElement(By.id("mat-input-6")).sendKeys("Propiedad frente a la Universidad");
        matInput6.sendKeys("Propiedad frente a la Universidad");

        //driver.findElement(By.id("mat-input-7")).click();
        WebElement matInput7 = driver.findElement(By.id("mat-input-7"));
        matInput7.click();
      /*  {
            WebElement element = driver.findElement(By.cssSelector(".submit-button > .mat-mdc-button-touch-target"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }*/
       // driver.findElement(By.id("mat-input-7")).sendKeys("Es un espacio amplio, comodo y el lugar es seguro.");
        matInput7.sendKeys("Es un espacio amplio, comodo y el lugar es seguro.");
        //driver.findElement(By.cssSelector(".submit-button > .mdc-button__label")).click();
        WebElement submitButton =driver.findElement(By.cssSelector(".submit-button > .mdc-button__label"));
        submitButton.click();
        //driver.findElement(By.cssSelector(".submit-button > .mdc-button__label")).click();
        submitButton =driver.findElement(By.cssSelector(".submit-button > .mdc-button__label"));
        submitButton.click();
    }
}
